server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: microservice-eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://microservice-eureka:8761/eureka/
