server:
  port: 8090

spring:
  application:
    name: msvc-student
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/studentDb
#    username: root
#    password: admin123
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: microservice-eureka
    client:
      service-url:
        defaultZone: http://${eureka.instance.hostname}:8761

springdoc:
  swagger-ui:
    path: /swagger-ui.html