server:
  port: 8080

eureka:
    client:
      service-url:
        defaultZone: http://microservice-eureka:8761/eureka/

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-student
          uri: lb://msvc-student
          predicates:
            - Path=/api/student/**
        - id: msvc-course
          uri: lb://msvc-course
          predicates:
            - Path=/api/course/**
