server:
  port: 9090

spring:
  application:
    name: msvc-course
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/coursesDb
#    username: postgres
#    password: admin
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: microservice-eureka
    client:
      service-url:
        defaultZone: http://${eureka.instance.hostname}:8761

springdoc:
  swagger-ui:
    path: /swagger-ui.html